### ISSUE TITLE
error: failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF

### ISSUE THREAD

**Issue by FBIanderson** [nydusaccelerator/buildkit#18]
when you use buildkit to run a command in container without exporting the image, it will cause a nil pointer dereference.
you can reproduce the error by just run this,  without the --output param is ok
```
buildctl   --timeout 30 build     --frontend=dockerfile.v0           --local context=.         --local dockerfile=.
```
below is the debug log of buildkit 
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11d84a4]

goroutine 1082 [running]:
github.com/moby/buildkit/solver/llbsolver.(*Solver).recordBuildHistory.func1.1({0x1b2ed00, 0xc0009a88c0}, 0xc000621f60?)
        /solver/llbsolver/solver.go:203 +0xc4
github.com/moby/buildkit/solver/llbsolver.(*Solver).recordBuildHistory.func1.2()
      /solver/llbsolver/solver.go:245 +0x51
golang.org/x/sync/errgroup.(*Group).Go.func1()
      /pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 695
       /pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0x96
```

**Comment by imeoer** [comment]
Thanks for reporting, fixed in `nydus-compression-type-enhance` branch.
